name: CI

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  node-js:
    name: Node.js
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.30.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install Packages
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run dev:lint:ci
